### ISSUE TITLE
Rss pages are not fully translated

### ISSUE THREAD

**Issue by lilyomo** [talengu/rss-translate#1]
This project is great.
However, the pages were not fully translated during own deployment. demo: https://cloudiver.github.io/Rss-Translation/rss/WRR.xml
What is the cause of this?

Thank you.

**Comment by talengu** [comment]
> This project is great. However, the pages were not fully translated during own deployment. demo: https://cloudiver.github.io/Rss-Translation/rss/WRR.xml What is the cause of this?
> 
> Thank you.

google translate api has a limit , maybe 5k words.
